### ISSUE TITLE
Dataset and Model Link does not work

### ISSUE THREAD

**Issue by PanagiotisFytas** [som-shahlab/ehrshot-benchmark#1]
Accessing the dataset and the model does not seem to work from the following link:

[Download the EHRSHOT dataset and pre-trained foundation model from the Stanford AIMI Center here](https://stanfordaimi.azurewebsites.net/datasets/72587f3f-45ab-43fc-8b54-7544c1d8bf51)

The page keeps saying "Loading Dataset Details..." without progressing.

**Comment by zhezhaozz** [comment]
The Page now says "The requested dataset is unavailable." 

Any update?

**Comment by Miking98** [comment]
Hi @PanagiotisFytas  and @zhezhaozz  -- Thank you for the message, and apologies for the confusion. There is a bit of red tape that we are currently sorting through given the sensitive nature of this dataset, but we hope to have things back up as soon as possible, and we will update the README.md accordingly once it is publicly available.

My sincere apologies for the delayed response, and thank you for your patience as we work to release what will hopefully be a unique asset for the community!

**Comment by njtp111** [comment]
HI @Miking98 , may I ask if the dataset is available for download

**Comment by GGGGFan** [comment]
Hi @Miking98, just wonder if there is any update on releasing the dataset. Thank you!

**Comment by Miking98** [comment]
Thanks for the message @GGGGFan and @njtp111 ! We are still working on having it released, but will update this thread as soon as possible. We apologize for the delay, but really appreciate the patience and are excited for it to be released!

**Comment by Miking98** [comment]
Hi @GGGGFan and @njtp111 . Thank you again so much for the patience.

We are still working on the dataset release, but the model's pretrained weights are now available on HuggingFace here! [https://huggingface.co/StanfordShahLab/clmbr-t-base](https://huggingface.co/StanfordShahLab/clmbr-t-base)

**Comment by amrit110** [comment]
Is the dataset available now? @GGGGFan @njtp111

**Comment by Miking98** [comment]
Hi @amrit110 thank you for the note -- We're getting very close! We have finished all of our internal approvals, and are aiming to have the full dataset available on either Redvis or GCP available in the coming weeks. Thank you again for your patience.

**Comment by amrit110** [comment]
Thanks @Miking98 ! Could you please let me know when it is available? I see there is a sample available through redivis.

**Comment by Miking98** [comment]
Hi @amrit110 @njtp111 @PanagiotisFytas @zhezhaozz I'm so sorry for the delay, but the dataset is now officially available here! https://redivis.com/datasets/53gc-8rhx41kgt
