### ISSUE TITLE
Not Available to sign in REDIVIS

### ISSUE THREAD

**Issue by gaeungaeun** [som-shahlab/ehrshot-benchmark#12]
Hello! Thank you for sharing such a great dataset and model!

As mentioned in the README, I would like to view the assets in REDIVIS, but it seems that I can't even sign in to the site.

How can I resolve this issue?

![스크린샷 2024-06-25 오후 3 56 41](https://github.com/som-shahlab/ehrshot-benchmark/assets/71487259/44953204-57fe-460c-b7bb-9615b4b11912)

**Comment by Miking98** [comment]
Hmm that is odd @gaeungaeun sorry for the confusion -- Could you try again / post the link you're using? For some reason it's working on my end, so maybe it resolved itself?

**Comment by gaeungaeun** [comment]
@Miking98 

I think I've solved it! 

I was getting an error when using my organization's email, but when I used my Google account, it worked! 

Thank you so much for checking it out for me!
