### ISSUE TITLE
splits.json is missing in EHRSHOT_ASSETS

### ISSUE THREAD

**Issue by Entodi** [som-shahlab/ehrshot-benchmark#15]
Hello,

I was trying to reproduce a quick start. However, when I run the bash script `9_make_cohort_plots.sh`, it says that the `splits.json` file is missing in the `EHRSHOT_ASSETS/splits` directory.

Does it have to be created by some other script, or must it come from Redivis? However, I did not find it in the files from Redivis.

Thank you.

**Comment by Miking98** [comment]
Hi @Entodi  -- This should be fixed in #17  -- there is no longer a `splits.json` file but a CSV containing the split.
